/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Role = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
  'pending' : IDL.Null,
});
export const User = IDL.Record({
  'householdId' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const Result_3 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const Day = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const Meal = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'dinner' : IDL.Null,
});
export const MealSlot = IDL.Record({
  'day' : Day,
  'recipeId' : IDL.Text,
  'meal' : Meal,
});
export const MealPlan = IDL.Record({
  'id' : IDL.Text,
  'householdId' : IDL.Text,
  'slots' : IDL.Vec(MealSlot),
  'weekStart' : IDL.Text,
});
export const Result_6 = IDL.Variant({ 'ok' : MealPlan, 'err' : IDL.Text });
export const Household = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});
export const Result_5 = IDL.Variant({ 'ok' : Household, 'err' : IDL.Text });
export const Ingredient = IDL.Record({
  'id' : IDL.Text,
  'defaultUnit' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'category' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Ingredient, 'err' : IDL.Text });
export const RecipeIngredient = IDL.Record({
  'unit' : IDL.Text,
  'quantity' : IDL.Float64,
  'ingredientId' : IDL.Text,
});
export const InstructionType = IDL.Variant({
  'freetext' : IDL.Null,
  'steps' : IDL.Null,
});
export const Recipe = IDL.Record({
  'id' : IDL.Text,
  'freetext' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'cookTime' : IDL.Nat,
  'isFavorite' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'steps' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'prepTime' : IDL.Nat,
  'instructionType' : InstructionType,
  'imageId' : IDL.Opt(IDL.Text),
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const Result_1 = IDL.Variant({ 'ok' : Recipe, 'err' : IDL.Text });
export const HouseholdJoinRequest = IDL.Record({
  'id' : IDL.Text,
  'householdId' : IDL.Text,
  'createdAt' : IDL.Int,
  'requesterName' : IDL.Text,
  'requesterId' : IDL.Principal,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(HouseholdJoinRequest),
  'err' : IDL.Text,
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text });
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(Household),
  'err' : IDL.Text,
});
export const ShoppingCartItem = IDL.Record({
  'householdId' : IDL.Text,
  'checked' : IDL.Bool,
  'unit' : IDL.Text,
  'category' : IDL.Text,
  'ingredientId' : IDL.Text,
  'totalQuantity' : IDL.Float64,
});
export const ShoppingCart = IDL.Record({
  'householdId' : IDL.Text,
  'items' : IDL.Vec(ShoppingCartItem),
  'weekStart' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text], [Result], []),
  'approveJoinRequest' : IDL.Func([IDL.Text], [Result_4], []),
  'approveUser' : IDL.Func([IDL.Principal], [Result_3], []),
  'assignRecipeToSlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_6],
      [],
    ),
  'clearAllData' : IDL.Func([], [Result_4], []),
  'clearWeek' : IDL.Func([IDL.Text], [Result], []),
  'createHousehold' : IDL.Func([IDL.Text], [Result_5], []),
  'createIngredient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_2], []),
  'createRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(RecipeIngredient),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'deleteIngredient' : IDL.Func([IDL.Text], [Result], []),
  'deleteRecipe' : IDL.Func([IDL.Text], [Result], []),
  'denyJoinRequest' : IDL.Func([IDL.Text], [Result_4], []),
  'denyUser' : IDL.Func([IDL.Principal], [Result_4], []),
  'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCurrentUser' : IDL.Func([], [Result_3], ['query']),
  'getHouseholdJoinRequests' : IDL.Func([], [Result_9], ['query']),
  'getHouseholdMembers' : IDL.Func([IDL.Text], [Result_7], ['query']),
  'getHouseholds' : IDL.Func([], [Result_8], ['query']),
  'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(Ingredient)], ['query']),
  'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getMealPlan' : IDL.Func([IDL.Text], [IDL.Opt(MealPlan)], ['query']),
  'getPendingUsers' : IDL.Func([], [Result_7], ['query']),
  'getRecipe' : IDL.Func([IDL.Text], [IDL.Opt(Recipe)], ['query']),
  'getRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getShoppingCart' : IDL.Func([IDL.Text], [ShoppingCart], ['query']),
  'getUsers' : IDL.Func([], [Result_7], ['query']),
  'leaveHousehold' : IDL.Func([], [Result_4], []),
  'registerOrGetUser' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'removeHouseholdMember' : IDL.Func([IDL.Principal], [Result_4], []),
  'removeRecipeFromSlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_6],
      [],
    ),
  'removeUser' : IDL.Func([IDL.Principal], [Result_4], []),
  'renameHousehold' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'requestJoinHousehold' : IDL.Func([IDL.Text], [Result_4], []),
  'toggleFavorite' : IDL.Func([IDL.Text], [Result_1], []),
  'transferAdminRole' : IDL.Func([IDL.Principal], [Result_4], []),
  'uncheckAllCartItems' : IDL.Func([IDL.Text], [Result], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [Result_3], []),
  'updateIngredient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'updateRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(RecipeIngredient),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'updateShoppingCartItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Role = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'pending' : IDL.Null,
  });
  const User = IDL.Record({
    'householdId' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const Result_3 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const Day = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const Meal = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const MealSlot = IDL.Record({
    'day' : Day,
    'recipeId' : IDL.Text,
    'meal' : Meal,
  });
  const MealPlan = IDL.Record({
    'id' : IDL.Text,
    'householdId' : IDL.Text,
    'slots' : IDL.Vec(MealSlot),
    'weekStart' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : MealPlan, 'err' : IDL.Text });
  const Household = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  const Result_5 = IDL.Variant({ 'ok' : Household, 'err' : IDL.Text });
  const Ingredient = IDL.Record({
    'id' : IDL.Text,
    'defaultUnit' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'category' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Ingredient, 'err' : IDL.Text });
  const RecipeIngredient = IDL.Record({
    'unit' : IDL.Text,
    'quantity' : IDL.Float64,
    'ingredientId' : IDL.Text,
  });
  const InstructionType = IDL.Variant({
    'freetext' : IDL.Null,
    'steps' : IDL.Null,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Text,
    'freetext' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'cookTime' : IDL.Nat,
    'isFavorite' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'steps' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'prepTime' : IDL.Nat,
    'instructionType' : InstructionType,
    'imageId' : IDL.Opt(IDL.Text),
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const Result_1 = IDL.Variant({ 'ok' : Recipe, 'err' : IDL.Text });
  const HouseholdJoinRequest = IDL.Record({
    'id' : IDL.Text,
    'householdId' : IDL.Text,
    'createdAt' : IDL.Int,
    'requesterName' : IDL.Text,
    'requesterId' : IDL.Principal,
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(HouseholdJoinRequest),
    'err' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Vec(Household), 'err' : IDL.Text });
  const ShoppingCartItem = IDL.Record({
    'householdId' : IDL.Text,
    'checked' : IDL.Bool,
    'unit' : IDL.Text,
    'category' : IDL.Text,
    'ingredientId' : IDL.Text,
    'totalQuantity' : IDL.Float64,
  });
  const ShoppingCart = IDL.Record({
    'householdId' : IDL.Text,
    'items' : IDL.Vec(ShoppingCartItem),
    'weekStart' : IDL.Text,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text], [Result], []),
    'approveJoinRequest' : IDL.Func([IDL.Text], [Result_4], []),
    'approveUser' : IDL.Func([IDL.Principal], [Result_3], []),
    'assignRecipeToSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_6],
        [],
      ),
    'clearAllData' : IDL.Func([], [Result_4], []),
    'clearWeek' : IDL.Func([IDL.Text], [Result], []),
    'createHousehold' : IDL.Func([IDL.Text], [Result_5], []),
    'createIngredient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'createRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(RecipeIngredient),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'deleteIngredient' : IDL.Func([IDL.Text], [Result], []),
    'deleteRecipe' : IDL.Func([IDL.Text], [Result], []),
    'denyJoinRequest' : IDL.Func([IDL.Text], [Result_4], []),
    'denyUser' : IDL.Func([IDL.Principal], [Result_4], []),
    'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCurrentUser' : IDL.Func([], [Result_3], ['query']),
    'getHouseholdJoinRequests' : IDL.Func([], [Result_9], ['query']),
    'getHouseholdMembers' : IDL.Func([IDL.Text], [Result_7], ['query']),
    'getHouseholds' : IDL.Func([], [Result_8], ['query']),
    'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(Ingredient)], ['query']),
    'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getMealPlan' : IDL.Func([IDL.Text], [IDL.Opt(MealPlan)], ['query']),
    'getPendingUsers' : IDL.Func([], [Result_7], ['query']),
    'getRecipe' : IDL.Func([IDL.Text], [IDL.Opt(Recipe)], ['query']),
    'getRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getShoppingCart' : IDL.Func([IDL.Text], [ShoppingCart], ['query']),
    'getUsers' : IDL.Func([], [Result_7], ['query']),
    'leaveHousehold' : IDL.Func([], [Result_4], []),
    'registerOrGetUser' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'removeHouseholdMember' : IDL.Func([IDL.Principal], [Result_4], []),
    'removeRecipeFromSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_6],
        [],
      ),
    'removeUser' : IDL.Func([IDL.Principal], [Result_4], []),
    'renameHousehold' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'requestJoinHousehold' : IDL.Func([IDL.Text], [Result_4], []),
    'toggleFavorite' : IDL.Func([IDL.Text], [Result_1], []),
    'transferAdminRole' : IDL.Func([IDL.Principal], [Result_4], []),
    'uncheckAllCartItems' : IDL.Func([IDL.Text], [Result], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [Result_3], []),
    'updateIngredient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'updateRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(RecipeIngredient),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'updateShoppingCartItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };