/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Day = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Household {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export interface HouseholdJoinRequest {
  'id' : string,
  'householdId' : string,
  'createdAt' : bigint,
  'requesterName' : string,
  'requesterId' : Principal,
}
export interface Ingredient {
  'id' : string,
  'defaultUnit' : string,
  'name' : string,
  'createdAt' : bigint,
  'category' : string,
}
export type InstructionType = { 'freetext' : null } |
  { 'steps' : null };
export type Meal = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'dinner' : null };
export interface MealPlan {
  'id' : string,
  'householdId' : string,
  'slots' : Array<MealSlot>,
  'weekStart' : string,
}
export interface MealSlot { 'day' : Day, 'recipeId' : string, 'meal' : Meal }
export interface Recipe {
  'id' : string,
  'freetext' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'cookTime' : bigint,
  'isFavorite' : boolean,
  'updatedAt' : bigint,
  'steps' : Array<string>,
  'notes' : string,
  'prepTime' : bigint,
  'instructionType' : InstructionType,
  'imageId' : [] | [string],
  'servings' : bigint,
  'ingredients' : Array<RecipeIngredient>,
}
export interface RecipeIngredient {
  'unit' : string,
  'quantity' : number,
  'ingredientId' : string,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = { 'ok' : Recipe } |
  { 'err' : string };
export type Result_2 = { 'ok' : Ingredient } |
  { 'err' : string };
export type Result_3 = { 'ok' : User } |
  { 'err' : string };
export type Result_4 = { 'ok' : null } |
  { 'err' : string };
export type Result_5 = { 'ok' : Household } |
  { 'err' : string };
export type Result_6 = { 'ok' : MealPlan } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<User> } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<Household> } |
  { 'err' : string };
export type Result_9 = { 'ok' : Array<HouseholdJoinRequest> } |
  { 'err' : string };
export type Role = { 'member' : null } |
  { 'admin' : null } |
  { 'pending' : null };
export interface ShoppingCart {
  'householdId' : string,
  'items' : Array<ShoppingCartItem>,
  'weekStart' : string,
}
export interface ShoppingCartItem {
  'householdId' : string,
  'checked' : boolean,
  'unit' : string,
  'category' : string,
  'ingredientId' : string,
  'totalQuantity' : number,
}
export interface User {
  'householdId' : [] | [string],
  'displayName' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
  'email' : string,
  'principalId' : Principal,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[string], Result>,
  'approveJoinRequest' : ActorMethod<[string], Result_4>,
  'approveUser' : ActorMethod<[Principal], Result_3>,
  'assignRecipeToSlot' : ActorMethod<
    [string, string, string, string],
    Result_6
  >,
  'clearAllData' : ActorMethod<[], Result_4>,
  'clearWeek' : ActorMethod<[string], Result>,
  'createHousehold' : ActorMethod<[string], Result_5>,
  'createIngredient' : ActorMethod<[string, string, string], Result_2>,
  'createRecipe' : ActorMethod<
    [
      string,
      Array<RecipeIngredient>,
      string,
      Array<string>,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      [] | [string],
      string,
    ],
    Result_1
  >,
  'deleteIngredient' : ActorMethod<[string], Result>,
  'deleteRecipe' : ActorMethod<[string], Result>,
  'denyJoinRequest' : ActorMethod<[string], Result_4>,
  'denyUser' : ActorMethod<[Principal], Result_4>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getCurrentUser' : ActorMethod<[], Result_3>,
  'getHouseholdJoinRequests' : ActorMethod<[], Result_9>,
  'getHouseholdMembers' : ActorMethod<[string], Result_7>,
  'getHouseholds' : ActorMethod<[], Result_8>,
  'getIngredient' : ActorMethod<[string], [] | [Ingredient]>,
  'getIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getMealPlan' : ActorMethod<[string], [] | [MealPlan]>,
  'getPendingUsers' : ActorMethod<[], Result_7>,
  'getRecipe' : ActorMethod<[string], [] | [Recipe]>,
  'getRecipes' : ActorMethod<[], Array<Recipe>>,
  'getShoppingCart' : ActorMethod<[string], ShoppingCart>,
  'getUsers' : ActorMethod<[], Result_7>,
  'leaveHousehold' : ActorMethod<[], Result_4>,
  'registerOrGetUser' : ActorMethod<[string, string], Result_3>,
  'removeHouseholdMember' : ActorMethod<[Principal], Result_4>,
  'removeRecipeFromSlot' : ActorMethod<[string, string, string], Result_6>,
  'removeUser' : ActorMethod<[Principal], Result_4>,
  'renameHousehold' : ActorMethod<[string, string], Result_5>,
  'requestJoinHousehold' : ActorMethod<[string], Result_4>,
  'toggleFavorite' : ActorMethod<[string], Result_1>,
  'transferAdminRole' : ActorMethod<[Principal], Result_4>,
  'uncheckAllCartItems' : ActorMethod<[string], Result>,
  'updateDisplayName' : ActorMethod<[string], Result_3>,
  'updateIngredient' : ActorMethod<[string, string, string, string], Result_2>,
  'updateRecipe' : ActorMethod<
    [
      string,
      string,
      Array<RecipeIngredient>,
      string,
      Array<string>,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      [] | [string],
      string,
    ],
    Result_1
  >,
  'updateShoppingCartItem' : ActorMethod<
    [string, string, string, boolean],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];