/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShoppingCart {
    householdId: string;
    items: Array<ShoppingCartItem>;
    weekStart: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: Ingredient;
} | {
    __kind__: "err";
    err: string;
};
export type Result_6 = {
    __kind__: "ok";
    ok: MealPlan;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    householdId?: string;
    displayName: string;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    principalId: Principal;
}
export interface MealSlot {
    day: Day;
    recipeId: string;
    meal: Meal;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Household;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: Array<HouseholdJoinRequest>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Recipe;
} | {
    __kind__: "err";
    err: string;
};
export interface ShoppingCartItem {
    householdId: string;
    checked: boolean;
    unit: string;
    category: string;
    ingredientId: string;
    totalQuantity: number;
}
export type Result_4 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface RecipeIngredient {
    unit: string;
    quantity: number;
    ingredientId: string;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export interface MealPlan {
    id: string;
    householdId: string;
    slots: Array<MealSlot>;
    weekStart: string;
}
export type Result_8 = {
    __kind__: "ok";
    ok: Array<Household>;
} | {
    __kind__: "err";
    err: string;
};
export interface Ingredient {
    id: string;
    defaultUnit: string;
    name: string;
    createdAt: bigint;
    category: string;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
};
export interface HouseholdJoinRequest {
    id: string;
    householdId: string;
    createdAt: bigint;
    requesterName: string;
    requesterId: Principal;
}
export interface Recipe {
    id: string;
    freetext: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    tags: Array<string>;
    cookTime: bigint;
    isFavorite: boolean;
    updatedAt: bigint;
    steps: Array<string>;
    notes: string;
    prepTime: bigint;
    instructionType: InstructionType;
    imageId?: string;
    servings: bigint;
    ingredients: Array<RecipeIngredient>;
}
export interface Household {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
}
export enum Day {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum InstructionType {
    freetext = "freetext",
    steps = "steps"
}
export enum Meal {
    breakfast = "breakfast",
    lunch = "lunch",
    dinner = "dinner"
}
export enum Role {
    member = "member",
    admin = "admin",
    pending = "pending"
}
export interface backendInterface {
    addCategory(name: string): Promise<Result>;
    approveJoinRequest(requestId: string): Promise<Result_4>;
    approveUser(userId: Principal): Promise<Result_3>;
    assignRecipeToSlot(weekStart: string, day: string, meal: string, recipeId: string): Promise<Result_6>;
    clearAllData(): Promise<Result_4>;
    clearWeek(weekStart: string): Promise<Result>;
    createHousehold(name: string): Promise<Result_5>;
    createIngredient(name: string, category: string, defaultUnit: string): Promise<Result_2>;
    createRecipe(name: string, recipeIngredients: Array<RecipeIngredient>, instructionType: string, steps: Array<string>, freetext: string, prepTime: bigint, cookTime: bigint, servings: bigint, tags: Array<string>, imageId: string | null, notes: string): Promise<Result_1>;
    deleteIngredient(id: string): Promise<Result>;
    deleteRecipe(id: string): Promise<Result>;
    denyJoinRequest(requestId: string): Promise<Result_4>;
    denyUser(userId: Principal): Promise<Result_4>;
    getAllTags(): Promise<Array<string>>;
    getCategories(): Promise<Array<string>>;
    getCurrentUser(): Promise<Result_3>;
    getHouseholdJoinRequests(): Promise<Result_9>;
    getHouseholdMembers(householdId: string): Promise<Result_7>;
    getHouseholds(): Promise<Result_8>;
    getIngredient(id: string): Promise<Ingredient | null>;
    getIngredients(): Promise<Array<Ingredient>>;
    getMealPlan(weekStart: string): Promise<MealPlan | null>;
    getPendingUsers(): Promise<Result_7>;
    getRecipe(id: string): Promise<Recipe | null>;
    getRecipes(): Promise<Array<Recipe>>;
    getShoppingCart(weekStart: string): Promise<ShoppingCart>;
    getUsers(): Promise<Result_7>;
    leaveHousehold(): Promise<Result_4>;
    registerOrGetUser(name: string, email: string): Promise<Result_3>;
    removeHouseholdMember(userId: Principal): Promise<Result_4>;
    removeRecipeFromSlot(weekStart: string, day: string, meal: string): Promise<Result_6>;
    removeUser(userId: Principal): Promise<Result_4>;
    renameHousehold(householdId: string, newName: string): Promise<Result_5>;
    requestJoinHousehold(householdId: string): Promise<Result_4>;
    toggleFavorite(id: string): Promise<Result_1>;
    transferAdminRole(newAdminId: Principal): Promise<Result_4>;
    uncheckAllCartItems(weekStart: string): Promise<Result>;
    updateProfile(displayName: string, email: string): Promise<Result_3>;
    updateIngredient(id: string, name: string, category: string, defaultUnit: string): Promise<Result_2>;
    updateRecipe(id: string, name: string, recipeIngredients: Array<RecipeIngredient>, instructionType: string, steps: Array<string>, freetext: string, prepTime: bigint, cookTime: bigint, servings: bigint, tags: Array<string>, imageId: string | null, notes: string): Promise<Result_1>;
    updateShoppingCartItem(weekStart: string, ingredientId: string, unit: string, checked: boolean): Promise<Result>;
}
import type { Day as _Day, Household as _Household, HouseholdJoinRequest as _HouseholdJoinRequest, Ingredient as _Ingredient, InstructionType as _InstructionType, Meal as _Meal, MealPlan as _MealPlan, MealSlot as _MealSlot, Recipe as _Recipe, RecipeIngredient as _RecipeIngredient, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, Role as _Role, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveJoinRequest(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJoinRequest(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJoinRequest(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveUser(arg0: Principal): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignRecipeToSlot(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRecipeToSlot(arg0, arg1, arg2, arg3);
                return from_candid_Result_6_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRecipeToSlot(arg0, arg1, arg2, arg3);
            return from_candid_Result_6_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllData(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearWeek(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.clearWeek(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearWeek(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHousehold(arg0: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.createHousehold(arg0);
                return from_candid_Result_5_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHousehold(arg0);
            return from_candid_Result_5_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createIngredient(arg0: string, arg1: string, arg2: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createIngredient(arg0, arg1, arg2);
                return from_candid_Result_2_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIngredient(arg0, arg1, arg2);
            return from_candid_Result_2_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecipe(arg0: string, arg1: Array<RecipeIngredient>, arg2: string, arg3: Array<string>, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: Array<string>, arg9: string | null, arg10: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg9), arg10);
                return from_candid_Result_1_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg9), arg10);
            return from_candid_Result_1_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteIngredient(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIngredient(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIngredient(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRecipe(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecipe(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecipe(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async denyJoinRequest(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.denyJoinRequest(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyJoinRequest(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async denyUser(arg0: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.denyUser(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyUser(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTags(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCurrentUser(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHouseholdJoinRequests(): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouseholdJoinRequests();
                return from_candid_Result_9_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouseholdJoinRequests();
            return from_candid_Result_9_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHouseholdMembers(arg0: string): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouseholdMembers(arg0);
                return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouseholdMembers(arg0);
            return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHouseholds(): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouseholds();
                return from_candid_Result_8_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouseholds();
            return from_candid_Result_8_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIngredient(arg0: string): Promise<Ingredient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIngredient(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIngredient(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIngredients();
            return result;
        }
    }
    async getMealPlan(arg0: string): Promise<MealPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlan(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlan(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingUsers(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingUsers();
                return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingUsers();
            return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipe(arg0: string): Promise<Recipe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipes();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipes();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoppingCart(arg0: string): Promise<ShoppingCart> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingCart(arg0);
            return result;
        }
    }
    async getUsers(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_Result_7_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveHousehold(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveHousehold();
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveHousehold();
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerOrGetUser(arg0: string, arg1: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrGetUser(arg0, arg1);
                return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrGetUser(arg0, arg1);
            return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeHouseholdMember(arg0: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHouseholdMember(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHouseholdMember(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeRecipeFromSlot(arg0: string, arg1: string, arg2: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRecipeFromSlot(arg0, arg1, arg2);
                return from_candid_Result_6_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRecipeFromSlot(arg0, arg1, arg2);
            return from_candid_Result_6_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeUser(arg0: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameHousehold(arg0: string, arg1: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.renameHousehold(arg0, arg1);
                return from_candid_Result_5_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameHousehold(arg0, arg1);
            return from_candid_Result_5_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestJoinHousehold(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.requestJoinHousehold(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestJoinHousehold(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleFavorite(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0);
                return from_candid_Result_1_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0);
            return from_candid_Result_1_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferAdminRole(arg0: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.transferAdminRole(arg0);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferAdminRole(arg0);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async uncheckAllCartItems(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.uncheckAllCartItems(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uncheckAllCartItems(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return from_candid_Result_3_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIngredient(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredient(arg0, arg1, arg2, arg3);
                return from_candid_Result_2_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredient(arg0, arg1, arg2, arg3);
            return from_candid_Result_2_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecipe(arg0: string, arg1: string, arg2: Array<RecipeIngredient>, arg3: string, arg4: Array<string>, arg5: string, arg6: bigint, arg7: bigint, arg8: bigint, arg9: Array<string>, arg10: string | null, arg11: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg10), arg11);
                return from_candid_Result_1_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg10), arg11);
            return from_candid_Result_1_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateShoppingCartItem(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShoppingCartItem(arg0, arg1, arg2, arg3);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShoppingCartItem(arg0, arg1, arg2, arg3);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Day_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Day): Day {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InstructionType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InstructionType): InstructionType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_MealPlan_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealPlan): MealPlan {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MealSlot_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealSlot): MealSlot {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Meal_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meal): Meal {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_User_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ingredient]): Ingredient | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MealPlan]): MealPlan | null {
    return value.length === 0 ? null : from_candid_MealPlan_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Recipe]): Recipe | null {
    return value.length === 0 ? null : from_candid_Recipe_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    householdId: string;
    slots: Array<_MealSlot>;
    weekStart: string;
}): {
    id: string;
    householdId: string;
    slots: Array<MealSlot>;
    weekStart: string;
} {
    return {
        id: value.id,
        householdId: value.householdId,
        slots: from_candid_vec_n16(_uploadFile, _downloadFile, value.slots),
        weekStart: value.weekStart
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _Day;
    recipeId: string;
    meal: _Meal;
}): {
    day: Day;
    recipeId: string;
    meal: Meal;
} {
    return {
        day: from_candid_Day_n19(_uploadFile, _downloadFile, value.day),
        recipeId: value.recipeId,
        meal: from_candid_Meal_n21(_uploadFile, _downloadFile, value.meal)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    freetext: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    tags: Array<string>;
    cookTime: bigint;
    isFavorite: boolean;
    updatedAt: bigint;
    steps: Array<string>;
    notes: string;
    prepTime: bigint;
    instructionType: _InstructionType;
    imageId: [] | [string];
    servings: bigint;
    ingredients: Array<_RecipeIngredient>;
}): {
    id: string;
    freetext: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    tags: Array<string>;
    cookTime: bigint;
    isFavorite: boolean;
    updatedAt: bigint;
    steps: Array<string>;
    notes: string;
    prepTime: bigint;
    instructionType: InstructionType;
    imageId?: string;
    servings: bigint;
    ingredients: Array<RecipeIngredient>;
} {
    return {
        id: value.id,
        freetext: value.freetext,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tags: value.tags,
        cookTime: value.cookTime,
        isFavorite: value.isFavorite,
        updatedAt: value.updatedAt,
        steps: value.steps,
        notes: value.notes,
        prepTime: value.prepTime,
        instructionType: from_candid_InstructionType_n32(_uploadFile, _downloadFile, value.instructionType),
        imageId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageId)),
        servings: value.servings,
        ingredients: value.ingredients
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    householdId: [] | [string];
    displayName: string;
    name: string;
    createdAt: bigint;
    role: _Role;
    email: string;
    principalId: Principal;
}): {
    householdId?: string;
    displayName: string;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    principalId: Principal;
} {
    return {
        householdId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.householdId)),
        displayName: value.displayName,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        email: value.email,
        principalId: value.principalId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    admin: null;
} | {
    pending: null;
}): Role {
    return "member" in value ? Role.member : "admin" in value ? Role.admin : "pending" in value ? Role.pending : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MealPlan;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MealPlan;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MealPlan_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): Day {
    return "tuesday" in value ? Day.tuesday : "wednesday" in value ? Day.wednesday : "saturday" in value ? Day.saturday : "thursday" in value ? Day.thursday : "sunday" in value ? Day.sunday : "friday" in value ? Day.friday : "monday" in value ? Day.monday : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakfast: null;
} | {
    lunch: null;
} | {
    dinner: null;
}): Meal {
    return "breakfast" in value ? Meal.breakfast : "lunch" in value ? Meal.lunch : "dinner" in value ? Meal.dinner : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Household;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Household;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Ingredient;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Ingredient;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Recipe;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Recipe;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Recipe_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freetext: null;
} | {
    steps: null;
}): InstructionType {
    return "freetext" in value ? InstructionType.freetext : "steps" in value ? InstructionType.steps : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_HouseholdJoinRequest>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<HouseholdJoinRequest>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_User>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n38(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Household>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Household>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MealSlot>): Array<MealSlot> {
    return value.map((x)=>from_candid_MealSlot_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n30(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
